<?php

namespace Alle80\Griglia\Console;

use Alle80\Griglia\Settings\AgentSettings;
use Alle80\Griglia\Settings\AppSettings;
use Alle80\Griglia\Settings\OptimizationSettings;
use Illuminate\Console\Command;
use Illuminate\Support\Facades\Artisan;

/**
 * `griglia:docs-generate` — writes the reference pages of the documentation from the code itself, so the
 * artisan commands, the config keys and the settings on the site can never drift from what the package
 * really does. Run by `griglia:docs-build` before every build.
 */
class DocsGenerate extends Command
{
    /** Symfony application inputs inherited at run time, not part of a package command's contract. */
    protected const GLOBAL_ARGUMENTS = ['command'];

    protected const GLOBAL_OPTIONS = ['help', 'silent', 'quiet', 'verbose', 'version', 'ansi', 'no-interaction', 'env'];

    protected $signature = 'griglia:docs-generate
        {--out= : Output directory (default: <package>/docs/reference)}
        {--check : Do not write; exit with 1 when a page is out of date}';

    protected $description = 'Generates the reference pages of the documentation (commands, config, settings) from the code';

    /** Pages this command owns, in nav order. */
    protected const PAGES = ['commands', 'config', 'settings'];

    /** Languages of the site: the first one is the base (no suffix), the others are written as `page.<lang>.md`. */
    protected const LANGUAGES = ['en', 'it'];

    /** Language being written right now — every renderer reads it through t() and chrome(). */
    protected string $lang = 'en';

    /** Catalogues (`resources/docs/reference.<lang>.php`), loaded once per run. */
    protected array $catalogues = [];

    /** Descriptions found in the code with no entry in the catalogue of the current language. */
    protected array $untranslated = [];

    public function handle(): int
    {
        $out = rtrim((string) ($this->option('out') ?: realpath(__DIR__.'/../..').'/docs/reference'), '/');
        if (! is_dir($out) && ! @mkdir($out, 0775, true)) {
            $this->error("cannot create $out");

            return self::FAILURE;
        }

        $stale = [];
        foreach (self::LANGUAGES as $lang) {
            $this->lang = $lang;
            foreach (self::PAGES as $page) {
                $file = "$out/$page".($lang === self::LANGUAGES[0] ? '' : ".$lang").'.md';
                $body = $this->{'render'.ucfirst($page)}();

                if ($this->option('check')) {
                    if (! is_file($file) || rtrim((string) file_get_contents($file)) !== rtrim($body)) {
                        $stale[] = basename($file);
                    }

                    continue;
                }

                file_put_contents($file, $body);
                $this->line("  <info>✓</info> $file");
            }
        }
        $this->reportUntranslated();

        if ($this->option('check')) {
            if ($stale) {
                $this->error('out of date: '.implode(', ', $stale).' — run `php artisan griglia:docs-generate`');
                $this->line('  (--check is meant for the package repository: inside a host app the pages'
                    .' legitimately differ — the settings list the providers installed there.)');

                return self::FAILURE;
            }
            $this->info('reference pages up to date');
        }

        return self::SUCCESS;
    }

    /** Header put on every generated page, so nobody edits them by hand. */
    protected function header(string $title, string $intro): string
    {
        return "# $title\n\n"
            .'<!-- '.$this->chrome('generated', 'Generated by `php artisan griglia:docs-generate` — do not edit by hand.')." -->\n\n"
            .$intro."\n\n";
    }

    // ----- languages --------------------------------------------------------

    /**
     * Translation of a string that comes from the code (a command description, a config comment): the
     * catalogue is keyed by the English source, so a new string simply stays English until someone
     * translates it — and reportUntranslated() says which ones are waiting.
     */
    protected function t(string $english): string
    {
        if ($this->lang === self::LANGUAGES[0] || $english === '' || $english === '—') {
            return $english;
        }
        $text = $this->catalogue()['text'] ?? [];
        if (isset($text[$english])) {
            return $text[$english];
        }
        $this->untranslated[$this->lang][$english] = true;

        return $english;
    }

    /** Translation of a fixed piece of the page itself (title, intro, table header). */
    protected function chrome(string $key, string $english): string
    {
        if ($this->lang === self::LANGUAGES[0]) {
            return $english;
        }

        return $this->catalogue()['pages'][$key] ?? $english;
    }

    protected function catalogue(): array
    {
        if (! array_key_exists($this->lang, $this->catalogues)) {
            $file = realpath(__DIR__.'/../..').'/resources/docs/reference.'.$this->lang.'.php';
            $this->catalogues[$this->lang] = is_file($file) ? (array) require $file : [];
        }

        return $this->catalogues[$this->lang];
    }

    /** Not an error: the pages are still generated, in English where a translation is missing. */
    protected function reportUntranslated(): void
    {
        foreach ($this->untranslated as $lang => $strings) {
            $strings = array_keys($strings);
            $this->warn(count($strings)." string(s) with no `$lang` translation in resources/docs/reference.$lang.php:");
            foreach (array_slice($strings, 0, 10) as $string) {
                $this->line('    '.$string);
            }
            if (count($strings) > 10) {
                $this->line('    … +'.(count($strings) - 10));
            }
        }
    }

    // ----- artisan commands ------------------------------------------------

    protected function renderCommands(): string
    {
        $md = $this->header(
            $this->chrome('commands_title', 'Artisan commands'),
            $this->chrome('commands_intro', 'Everything the package adds to `php artisan`, straight from the command definitions.')
        );

        $commands = collect(Artisan::all())
            ->filter(fn ($c, $name) => str_starts_with((string) $name, 'griglia:'))
            ->sortKeys();

        foreach ($commands as $name => $command) {
            $md .= "## `$name`\n\n";
            $md .= $this->t(trim((string) $command->getDescription()))."\n\n";

            $aliases = array_filter($command->getAliases(), fn ($a) => $a !== $name);
            if ($aliases) {
                $md .= $this->chrome('alias', 'Alias').': '.implode(', ', array_map(fn ($a) => "`$a`", $aliases))."\n\n";
            }

            $md .= '```bash'."\n".'php artisan '.$command->getSynopsis()."\n".'```'."\n\n";

            $rows = [];
            foreach ($command->getDefinition()->getArguments() as $arg) {
                if (in_array($arg->getName(), self::GLOBAL_ARGUMENTS, true)) {
                    continue;
                }
                $rows[] = ['`'.$arg->getName().'`', $this->t($arg->getDescription() ?: '—'), $arg->isRequired() ? $this->chrome('required', 'required') : $this->def($arg->getDefault())];
            }
            foreach ($command->getDefinition()->getOptions() as $opt) {
                if (in_array($opt->getName(), self::GLOBAL_OPTIONS, true)) {
                    continue;
                }
                $rows[] = ['`--'.$opt->getName().'`', $this->t($opt->getDescription() ?: '—'), $opt->acceptValue() ? $this->def($opt->getDefault()) : $this->chrome('flag', 'flag')];
            }
            if ($rows) {
                $md .= '| '.$this->chrome('col_option', 'Argument / option').' | '.$this->chrome('col_what', 'What it does')
                    .' | '.$this->chrome('col_default', 'Default')." |\n|---|---|---|\n";
                foreach ($rows as [$n, $d, $v]) {
                    $md .= "| $n | ".$this->cell($d).' | '.$v." |\n";
                }
                $md .= "\n";
            }
        }

        return $md;
    }

    // ----- config file -----------------------------------------------------

    protected function renderConfig(): string
    {
        $md = $this->header(
            $this->chrome('config_title', 'Configuration file'),
            $this->chrome(
                'config_intro',
                "Every key of `config/griglia.php` — publish it with `php artisan vendor:publish --tag=griglia-config`.\n"
                .'Decided by whoever installs the package; the run-time options live in [Settings](settings.md).'
            )
        );

        $md .= '| '.$this->chrome('col_key', 'Key').' | '.$this->chrome('col_env', 'Environment variable')
            .' | '.$this->chrome('col_default', 'Default').' | '.$this->chrome('col_whatis', 'What it is')
            ." |\n|---|---|---|---|\n";

        $comment = [];
        foreach (file(realpath(__DIR__.'/../..').'/config/griglia.php') as $line) {
            $trim = trim($line);

            if (str_starts_with($trim, '//')) {
                $comment[] = trim(substr($trim, 2));

                continue;
            }
            if ($trim === '' || str_starts_with($trim, '/*') || str_starts_with($trim, '*')) {
                $comment = $trim === '' ? [] : $comment;

                continue;
            }
            // Only top-level keys: they are indented with exactly four spaces.
            if (! preg_match('/^ {4}\'([a-z0-9_]+)\'\s*=>\s*(.*)$/i', rtrim($line), $m)) {
                continue;
            }

            [, $key, $value] = $m;
            $value = rtrim($value, ',');
            $env = preg_match("/env\(\s*'([A-Z0-9_]+)'/", $value, $e) ? '`'.$e[1].'`' : '—';
            $default = $this->configDefault($value);

            // The comment above a block describes every key of that block: keep it until a blank line.
            $md .= "| `$key` | $env | $default | ".$this->cell($this->t(trim(implode(' ', $comment))))." |\n";
        }

        return $md;
    }

    /** Readable default for a config line: the second argument of env(), or the literal value. */
    protected function configDefault(string $value): string
    {
        if (str_starts_with($value, '[')) {
            return '_array_';
        }
        if (preg_match("/^env\(\s*'[A-Z0-9_]+'\s*\)$/", $value)) {
            return '—';    // env() with no fallback: the default is null
        }
        if (preg_match("/env\(\s*'[A-Z0-9_]+'\s*,\s*(.+)\)$/", $value, $m)) {
            $value = trim($m[1]);
        }
        $value = trim($value);

        return $value === '' ? '—' : '`'.str_replace('|', '\|', $value).'`';
    }

    // ----- settings --------------------------------------------------------

    protected function renderSettings(): string
    {
        // The locale of the page, not the one of whoever runs the command (and a neutral agent name):
        // the page must be the same everywhere, or `--check` would never be green.
        $locale = app()->getLocale();
        app()->setLocale($this->lang);

        try {
            return $this->settingsBody();
        } finally {
            app()->setLocale($locale);
        }
    }

    protected function settingsBody(): string
    {
        $md = $this->header(
            $this->chrome('settings_title', 'Settings'),
            $this->chrome(
                'settings_intro',
                'The options of the `/settings` page: stored in the database, changed at run time, no deploy. '
                .'Labels and help are the ones the page shows (here in the English base language).'
            )
        );

        $groups = [
            'agent' => [__('griglia::t.settings_agent_title', ['agent' => $this->chrome('the_agent', 'the agent')]), AgentSettings::fields()],
            'optimization' => [__('griglia::t.settings_optimization_title'), OptimizationSettings::fields()],
            'app' => [__('griglia::t.settings_app_title'), AppSettings::fields()],
        ];

        foreach ($groups as $group => [$title, $fields]) {
            $md .= "## $title (`$group`)\n\n";
            $md .= '| '.$this->chrome('col_setting', 'Setting').' | '.$this->chrome('col_type', 'Type')
                .' | '.$this->chrome('col_what', 'What it does')." |\n|---|---|---|\n";

            // Options straight from the translations, not from the field: part of them is injected at
            // run time (the AI providers installed in the app) and the page must stay the same everywhere.
            $translated = (array) __('griglia::t.settings_options');

            foreach ($fields as $key => $field) {
                [$label, $help, $type] = $field;
                $options = is_array($translated[$key] ?? null) ? $translated[$key] : [];
                $type = $options ? $type.': '.implode(', ', array_map(fn ($v) => "`$v`", array_keys($options))) : $type;
                $md .= '| **'.$this->cell($label)."** (`$key`) | ".$this->cell($type).' | '.$this->cell($help)." |\n";
            }
            $md .= "\n";
        }

        return $md;
    }

    // ----- helpers ---------------------------------------------------------

    protected function def(mixed $value): string
    {
        return match (true) {
            $value === null, $value === '' => '—',
            $value === true => '`true`',
            $value === false => '`false`',
            is_array($value) => '_array_',
            default => '`'.$value.'`',
        };
    }

    /** Table cell: no pipes, no newlines. */
    protected function cell(string $text): string
    {
        return trim(str_replace(['|', "\n"], ['\|', ' '], $text));
    }
}
