<?php

namespace Alle80\Griglia\Console;

use Alle80\Griglia\Settings\AgentSettings;
use Alle80\Griglia\Settings\AppSettings;
use Alle80\Griglia\Settings\OptimizationSettings;
use Illuminate\Console\Command;
use Illuminate\Support\Facades\Artisan;

/**
 * `griglia:docs-generate` — writes the reference pages of the documentation from the code itself, so the
 * artisan commands, the config keys and the settings on the site can never drift from what the package
 * really does. Run by `griglia:docs-build` before every build.
 */
class DocsGenerate extends Command
{
    protected $signature = 'griglia:docs-generate
        {--out= : Output directory (default: <package>/docs/reference)}
        {--check : Do not write; exit with 1 when a page is out of date}';

    protected $description = 'Generates the reference pages of the documentation (commands, config, settings) from the code';

    /** Pages this command owns, in nav order. */
    protected const PAGES = ['commands', 'config', 'settings'];

    public function handle(): int
    {
        $out = rtrim((string) ($this->option('out') ?: realpath(__DIR__.'/../..').'/docs/reference'), '/');
        if (! is_dir($out) && ! @mkdir($out, 0775, true)) {
            $this->error("cannot create $out");

            return self::FAILURE;
        }

        $stale = [];
        foreach (self::PAGES as $page) {
            $file = "$out/$page.md";
            $body = $this->{'render'.ucfirst($page)}();

            if ($this->option('check')) {
                if (! is_file($file) || rtrim((string) file_get_contents($file)) !== rtrim($body)) {
                    $stale[] = basename($file);
                }

                continue;
            }

            file_put_contents($file, $body);
            $this->line("  <info>✓</info> $file");
        }

        if ($this->option('check')) {
            if ($stale) {
                $this->error('out of date: '.implode(', ', $stale).' — run `php artisan griglia:docs-generate`');

                return self::FAILURE;
            }
            $this->info('reference pages up to date');
        }

        return self::SUCCESS;
    }

    /** Header put on every generated page, so nobody edits them by hand. */
    protected function header(string $title, string $intro): string
    {
        return "# $title\n\n"
            ."<!-- Generated by `php artisan griglia:docs-generate` — do not edit by hand. -->\n\n"
            .$intro."\n\n";
    }

    // ----- artisan commands ------------------------------------------------

    protected function renderCommands(): string
    {
        $md = $this->header(
            'Artisan commands',
            'Everything the package adds to `php artisan`, straight from the command definitions.'
        );

        $commands = collect(Artisan::all())
            ->filter(fn ($c, $name) => str_starts_with((string) $name, 'griglia:'))
            ->sortKeys();

        foreach ($commands as $name => $command) {
            $md .= "## `$name`\n\n";
            $md .= trim((string) $command->getDescription())."\n\n";

            $aliases = array_filter($command->getAliases(), fn ($a) => $a !== $name);
            if ($aliases) {
                $md .= 'Alias: '.implode(', ', array_map(fn ($a) => "`$a`", $aliases))."\n\n";
            }

            $md .= '```bash'."\n".'php artisan '.$command->getSynopsis()."\n".'```'."\n\n";

            $rows = [];
            foreach ($command->getDefinition()->getArguments() as $arg) {
                $rows[] = ['`'.$arg->getName().'`', $arg->getDescription() ?: '—', $arg->isRequired() ? 'required' : $this->def($arg->getDefault())];
            }
            foreach ($command->getDefinition()->getOptions() as $opt) {
                $rows[] = ['`--'.$opt->getName().'`', $opt->getDescription() ?: '—', $opt->acceptValue() ? $this->def($opt->getDefault()) : 'flag'];
            }
            if ($rows) {
                $md .= "| Argument / option | What it does | Default |\n|---|---|---|\n";
                foreach ($rows as [$n, $d, $v]) {
                    $md .= "| $n | ".$this->cell($d).' | '.$v." |\n";
                }
                $md .= "\n";
            }
        }

        return $md;
    }

    // ----- config file -----------------------------------------------------

    protected function renderConfig(): string
    {
        $md = $this->header(
            'Configuration file',
            "Every key of `config/griglia.php` — publish it with `php artisan vendor:publish --tag=griglia-config`.\n"
            .'Decided by whoever installs the package; the run-time options live in [Settings](settings.md).'
        );

        $md .= "| Key | Environment variable | Default | What it is |\n|---|---|---|---|\n";

        $comment = [];
        foreach (file(realpath(__DIR__.'/../..').'/config/griglia.php') as $line) {
            $trim = trim($line);

            if (str_starts_with($trim, '//')) {
                $comment[] = trim(substr($trim, 2));

                continue;
            }
            if ($trim === '' || str_starts_with($trim, '/*') || str_starts_with($trim, '*')) {
                $comment = $trim === '' ? [] : $comment;

                continue;
            }
            // Only top-level keys: they are indented with exactly four spaces.
            if (! preg_match('/^ {4}\'([a-z0-9_]+)\'\s*=>\s*(.*)$/i', rtrim($line), $m)) {
                continue;
            }

            [, $key, $value] = $m;
            $value = rtrim($value, ',');
            $env = preg_match("/env\(\s*'([A-Z0-9_]+)'/", $value, $e) ? '`'.$e[1].'`' : '—';
            $default = $this->configDefault($value);

            // The comment above a block describes every key of that block: keep it until a blank line.
            $md .= "| `$key` | $env | $default | ".$this->cell(implode(' ', $comment))." |\n";
        }

        return $md;
    }

    /** Readable default for a config line: the second argument of env(), or the literal value. */
    protected function configDefault(string $value): string
    {
        if (str_starts_with($value, '[')) {
            return '_array_';
        }
        if (preg_match("/^env\(\s*'[A-Z0-9_]+'\s*\)$/", $value)) {
            return '—';    // env() with no fallback: the default is null
        }
        if (preg_match("/env\(\s*'[A-Z0-9_]+'\s*,\s*(.+)\)$/", $value, $m)) {
            $value = trim($m[1]);
        }
        $value = trim($value);

        return $value === '' ? '—' : '`'.str_replace('|', '\|', $value).'`';
    }

    // ----- settings --------------------------------------------------------

    protected function renderSettings(): string
    {
        // Always the English base language and a neutral agent name: the page must not change with the
        // locale (or the agent) of whoever runs the command, or `--check` would never be green.
        $locale = app()->getLocale();
        app()->setLocale('en');

        try {
            return $this->settingsBody();
        } finally {
            app()->setLocale($locale);
        }
    }

    protected function settingsBody(): string
    {
        $md = $this->header(
            'Settings',
            'The options of the `/settings` page: stored in the database, changed at run time, no deploy. '
            .'Labels and help are the ones the page shows (here in the English base language).'
        );

        $groups = [
            'agent' => [__('griglia::t.settings_agent_title', ['agent' => 'the agent']), AgentSettings::fields()],
            'optimization' => [__('griglia::t.settings_optimization_title'), OptimizationSettings::fields()],
            'app' => [__('griglia::t.settings_app_title'), AppSettings::fields()],
        ];

        foreach ($groups as $group => [$title, $fields]) {
            $md .= "## $title (`$group`)\n\n";
            $md .= "| Setting | Type | What it does |\n|---|---|---|\n";

            foreach ($fields as $key => $field) {
                [$label, $help, $type] = $field;
                $options = $field[3] ?? [];
                $type = $options ? $type.': '.implode(', ', array_map(fn ($v) => "`$v`", array_keys($options))) : $type;
                $md .= '| **'.$this->cell($label)."** (`$key`) | ".$this->cell($type).' | '.$this->cell($help)." |\n";
            }
            $md .= "\n";
        }

        return $md;
    }

    // ----- helpers ---------------------------------------------------------

    protected function def(mixed $value): string
    {
        return match (true) {
            $value === null, $value === '' => '—',
            $value === true => '`true`',
            $value === false => '`false`',
            is_array($value) => '_array_',
            default => '`'.$value.'`',
        };
    }

    /** Table cell: no pipes, no newlines. */
    protected function cell(string $text): string
    {
        return trim(str_replace(['|', "\n"], ['\|', ' '], $text));
    }
}
